num1=int(input('enter your first number'))
num2=int(input('enter your second number'))
num3=int(input('enter your third number'))

print(num1+num2+num3)
print(num2-num1)
print(num1-num2)
print(num1-num3)
print(num3-num2)
print(num3-num1)
print(num2-num3)
print(num2/num1)
print(num1/num2)
print(num3/num1)
print(num2/num3)
print(num3/num2)
print(num3/num1)
print(num1*num2)
print(num3*num1)
print(num3*num2)
print(num1*num2*num3)